#!/bin/bash

set -e

build=false

if [[ "$1" == "--build" ]]; then
  build=true
  echo "Running with --build, paperclip jar will be created."
fi

echo "Building development environment"
./gradlew applyAllPatches

if $build; then
    echo "Building paperclip jar"
    ./gradlew createPaperclipJar
fi
