#!/bin/bash

set -e

if [ -z "$1" ]; then
  echo "Error: The 'commitName' argument must be specified."
  exit 1
fi

COMMIT_NAME="$1"
JUST_SERVER=${2:-false}

echo "Building feature commit of \"$COMMIT_NAME\""

declare -A gradle_tasks

git_commit() {
  local dir="$1"
  local message="$2"
  local gradle_task="$3"

  if [ ! -d "$dir" ]; then
    echo "Error: The directory '$dir' does not exist or is not valid."
    exit 1
  fi

  cd "$dir"

  if ! git diff --quiet || ! git diff --cached --quiet; then
    git add .
    git commit -m "$message"
    echo "Completed commit in directory $dir"
    gradle_tasks["$gradle_task"]="true"
  else
    echo "No changes to commit in $dir"
  fi

  cd - > /dev/null
}

run_gradle_task() {
  local task="$1"
  if [ "${gradle_tasks[$task]}" = "true" ]; then
    echo "Running Gradle task: $task"
    ./gradlew "$task"
    if [ $? -ne 0 ]; then
      echo "Gradle task '$task' failed."
      exit 1
    fi
    echo "Gradle task '$task' completed successfully."
  else
    echo "Skipping Gradle task '$task' as no changes were committed in its directory."
  fi
}

git_commit "./purpur-server/" "$COMMIT_NAME" "rebuildPurpurServerFeaturePatches"
git_commit "./purpur-api/" "$COMMIT_NAME" "rebuildPurpurApiFeaturePatches"
git_commit "./paper-server/" "$COMMIT_NAME" "rebuildPaperServerFeaturePatches"
git_commit "./paper-api/" "$COMMIT_NAME" "rebuildPaperApiFeaturePatches"
git_commit "./canvas-server/src/minecraft/java" "$COMMIT_NAME" "rebuildMinecraftFeaturePatches"

echo "Running API rebuilding..."
run_gradle_task "rebuildPurpurApiFeaturePatches"
run_gradle_task "rebuildPaperApiFeaturePatches"

echo "Running Server rebuilding..."
run_gradle_task "rebuildPurpurServerFeaturePatches"
run_gradle_task "rebuildPaperServerFeaturePatches"
run_gradle_task "rebuildMinecraftFeaturePatches"
