group = io.canvasmc.canvas

# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion = 26.2
mcVersion = 26.2
channel = STABLE

paperRef = 1f7285664c3a11690a641e19ffcc90321fcc7fde

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx4G
