group = io.canvasmc.canvas

# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion = 26.3
mcVersion = 26.3
channel = ALPHA

paperRef = 93c9b2ab1f4efdd23654064f562a7db41e6397c7

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx4G
