group = io.canvasmc.canvas

# This is the current API version for use in (paper-)plugin.yml files
# During snapshot cycles this should be the anticipated version of the release target
apiVersion = 26.2
mcVersion = 26.2
channel = BETA

paperRef = 8a52ce8c27894a771b9a57b262ffb027c6d4ae25

org.gradle.configuration-cache = true
org.gradle.caching = true
org.gradle.parallel = true
org.gradle.vfs.watch = false
org.gradle.jvmargs = -Xmx4G
