name: "Bug Report"
description: "Report a bug in Canvas"
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: "## 🐞 Bug Report\nDescribe the issue clearly and provide necessary details."
  - type: textarea
    id: bug-description
    attributes:
      label: "Describe the Bug"
      description: "What happened? What did you expect?"
      placeholder: "When I do X, Y happens instead of Z."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the issue."
      placeholder: |
        1. Load the server
        2. Run command X
        3. See unexpected behavior
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs & Screenshots"
      description: "Provide logs or screenshots if applicable. Please include a spark report aswell if relevant with the argument `--thread *`"
      render: shell
  - type: input
    id: canvas-version
    attributes:
      label: "Canvas Version"
      placeholder: "e.g., 1.21.4"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any other information that may help debug the bug."
