name: "Crash Report"
description: "Report a crash in Canvas"
labels: ["crash", "bug"]
body:
  - type: markdown
    attributes:
      value: "## 🚨 Crash Report\nPlease fill out the details below to help us diagnose the issue."
  - type: textarea
    id: crash-description
    attributes:
      label: "Describe the crash"
      description: "Provide a detailed description of the crash, including what you were doing when it happened, what plugins are installed, etc."
      placeholder: "Canvas crashed when..."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "List the steps to reproduce the crash."
      placeholder: |
        1. Start the server
        2. Load world
        3. Crash occurs
    validations:
      required: true
  - type: textarea
    id: crash-logs
    attributes:
      label: "Crash Logs"
      description: "Paste relevant crash logs or attach a file."
      render: shell
  - type: input
    id: canvas-version
    attributes:
      label: "Canvas Version"
      placeholder: "e.g., 1.21.4"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any other information that may help debug the crash."
