name: "Performance Issue"
description: "Report a performance issue in Canvas"
labels: ["bug", "performance"]
body:
  - type: markdown
    attributes:
      value: "## 🚀 Performance Issue\nDescribe performance-related problems clearly."
  - type: textarea
    id: performance-description
    attributes:
      label: "Describe the Issue"
      description: "Explain the performance issue and when it occurs."
      placeholder: "Server TPS becomes unstable when..."
    validations:
      required: true
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: "Steps to Reproduce"
      description: "Provide detailed steps to observe the performance drop."
      placeholder: |
        1. Start the server
        2. Load world
        3. Do an action
    validations:
      required: true
  - type: textarea
    id: logs
    attributes:
      label: "Logs & Spark"
      description: "Attach relevant logs and/or a spark report with the argument `--thread *`"
      render: shell
  - type: input
    id: hardware-specs
    attributes:
      label: "Hardware Specs"
      placeholder: "CPU: Intel i7, RAM: 16GB, etc."
    validations:
      required: true
  - type: input
    id: canvas-version
    attributes:
      label: "Canvas Version"
      placeholder: "e.g., 1.21.4"
    validations:
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Any extra details that could help."
