name: PR

on:
  workflow_dispatch:
  pull_request:
    branches:
      - "master"
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3.6.0
        with:
          distribution: temurin
          java-version: 22
          cache: 'gradle'
      - name: Setup Node-14
        uses: actions/setup-node@v2
        with:
          node-version: '14'
      - name: Install dayjs
        run: npm install dayjs
      - name: Batch and Deploy
        run: |
          git config --global user.email "no-reply@github.com" && git config --global user.name "Github Actions"
          ./gradlew applyPatches --no-daemon
          ./gradlew createCanvasServer --no-daemon
      - name: Fallback
        if: ${{ failure() }}
        run: |
          ./gradlew clean cleanCache
          ./gradlew applyPatches --no-daemon
          ./gradlew createCanvasServer --no-daemon
