name: Test-PR

on:
  pull_request:

permissions:
  contents: read

concurrency:
  group: test-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Java 25
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "25"

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

      - name: Apply all patches
        run: ./gradlew applyAllPatches

      - name: Rebuild patches
        run: |
          ./gradlew \
            rebuildAllServerPatches \
            rebuildPaperApiPatches \
            rebuildPaperSingleFilePatches

      - name: Check rebuilt patches have no changes
        run: |
         git diff --exit-code
         git diff --cached --exit-code

      - name: Run tests
        run: ./gradlew test
