name: Create download api testing
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set Commit Hash
        id: set_commit_hash
        run: echo "COMMIT_HASH=$(git log --format='%H' -n 1)" >> $GITHUB_ENV
        
